project:
  type: website
  output-dir: docs
  resources:
    - media
    - files

website:
  title: "Chloe Ostermann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - more.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

