project:
  type: website
  output-dir: docs
  resources:
    - media
    - files

website:
  title: "chloeostermann.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
      - more.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

