project:
  type: website
  output-dir: docs
  resources:
    - media/**
    - files/**

website:
  title: "Chloe Ostermann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - more.qmd
page-layout: full

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

